### ISSUE TITLE
Prisma 2 introspection fails

### ISSUE THREAD

**Issue by nikolasburk** [prisma/next#22]
I've just tried the `prisma2 introspect` command. I've used a local PostgreSQL database which I've set up through Docker:

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            # rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```

I then created the initial schema using Prisma, but using custom table names. Here is the datamodel I used to setup my database schema:

```graphql
type User @db(name: "users") {
  id: ID! @id
  createdAt: DateTime! @createdAt
  email: String! @unique
  name: String
  role: Role @default(value: USER)
  posts: [Post!]!
  profile: Profile @relation(link: INLINE)
}

type Profile @db(name: "profile") {
  id: ID! @id
  user: User!
  bio: String!
}

type Post @db(name: "posts") {
  id: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  title: String!
  published: Boolean! @default(value: false)
  author: User!
  categories: [Category!]! @relation(name: "PostToCategory")
}

type Category @db(name: "categories") {
  id: ID! @id
  name: String!
  posts: [Post!]! @relation(link: TABLE, name: "PostToCategory")
}

type PostToCategory @db(name: "post_to_category_relation") @relationTable {
  post: Post
  category: Category
}

enum Role {
  USER
  ADMIN
}
```

(I've migrated using `prisma deploy`.)

I then installed the latest version of the Prisma 2 CLI and ran `prisma2 introspect`. I successfully connected to the DB:

![image](https://user-images.githubusercontent.com/4058327/59210595-3c139f00-8bae-11e9-905d-e1f0aeb147e4.png)

Then selected my schema:

![image](https://user-images.githubusercontent.com/4058327/59210623-4f266f00-8bae-11e9-857b-a9a2e0324de4.png)

This is the error message I then get:

```
Select the schema you want to introspect

 ✖  Error in lift engine for rpc convertDmmfToDml:
      [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:33] m.make::<barrel::backend::Sqlite>() = "CREATE TABLE IF NOT EXISTS \"migration_engine\".\"_Migration\" (\"revision\" INTEGER NOT NULL PRIMARY KE
Y, \"name\" TEXT NOT NULL, \"datamodel\" TEXT NOT NULL, \"status\" TEXT NOT NULL, \"applied\" INTEGER NOT NULL, \"rolled_back\" INTEGER NOT NULL, \"datamodel_steps\" TEXT NOT NULL, \"database_migration\" TEXT NOT NULL, \"errors\" TEXT NOT 
NULL, \"started_at\" DATE NOT NULL, \"finished_at\" DATE);"
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QueryError(SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database: /Users/nikolasburk/Desktop/prisma2-introspection/db/migratio
n_engine.db"))

    stack backtrace:
       0: backtrace::backtrace::trace::h862903ac52cf58ce (0x101c1afce)
       1: backtrace::capture::Backtrace::new_unresolved::hb838890310508129 (0x101c1a198)
       2: failure::backtrace::internal::InternalBacktrace::new::he7020c6c20003af5 (0x101c19b39)
       3: <failure::backtrace::Backtrace as core::default::Default>::default::hbdcce0dc805803fe (0x101c19d25)
       4: prisma_query::connector::sqlite::<impl core::convert::From<rusqlite::error::Error> for prisma_query::error::Error>::from::h79eaa967bb9b5129 (0x1019d75a6)
       5: prisma_query::connector::sqlite::Sqlite::attach_database::h32308026c6c86b4b (0x1019c19cb)
       6: <prisma_query::connector::sqlite::Sqlite as prisma_query::transaction::Connectional>::with_connection::h3cffc4af6dba39da (0x101925f56)
       7: <sql_migration_connector::sql_migration_persistence::SqlMigrationPersistence<C>>::init::he908b845b7ceac5b (0x101935bcc)
       8: <F as jsonrpc_core::calls::RpcMethodSimple>::call::hc0b1ef25c89a7be5 (0x1018f905e)
       9: <F as jsonrpc_core::calls::RpcMethod<T>>::call::h9efcd23f8be9fc5b (0x1018b1fcc)
      10: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::h3d1b435ca4e95c94 (0x1018b9582)
      11: <futures::future::chain::Chain<A, B, C>>::poll::h9417e743b0884fbf (0x1018ac810)
      12: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::hc1de95f3c2a0e42b (0x1018a400e)
      13: <futures::future::map::Map<A, F> as futures::future::Future>::poll::hadd77e65c7fd1f79 (0x1018c1a5f)
      14: <futures::future::either::Either<A, B> as futures::future::Future>::poll::h01c922ccc6fa78dc (0x1018b9810)
      15: futures::task_impl::std::set::h829b7bbe698f472f (0x1018f2dcf)
      16: futures::task_impl::std::ThreadNotify::with_current::hd36b29258f5bbbc2 (0x1018f2a51)
      17: futures::future::Future::wait::h67e3c6888e051b25 (0x1018c16e3)
      18: <jsonrpc_core::io::IoHandler<M>>::handle_request_sync::hfa6a2f10b2714dff (0x1018afd8f)
      19: migration_core::rpc_api::RpcApi::handle::h176bad87cf66f5e8 (0x1018fac0b)
      20: migration_engine::main::h59aad957f6ba49cc (0x10187d45d)
      21: std::rt::lang_start::{{closure}}::h52a1cb7acf5ab7bd (0x10187d406)
      22: std::panicking::try::do_call::h20c95c457c762d5f (0x101c2fed8)
      23: ___rust_maybe_catch_panic (0x101c32eff)
      24: std::rt::lang_start_internal::he82d111f45e8971a (0x101c308fe)
      25: _main (0x10187d4b9))', src/libcore/result.rs:997:5
    stack backtrace:
       0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
       1: std::sys_common::backtrace::_print
       2: std::panicking::default_hook::{{closure}}
       3: std::panicking::default_hook
       4: std::panicking::rust_panic_with_hook
       5: std::panicking::continue_panic_fmt
       6: rust_begin_unwind
       7: core::panicking::panic_fmt
       8: core::result::unwrap_failed
       9: <sql_migration_connector::sql_migration_persistence::SqlMigrationPersistence<C>>::init
      10: <F as jsonrpc_core::calls::RpcMethodSimple>::call
      11: <F as jsonrpc_core::calls::RpcMethod<T>>::call
      12: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll
      13: <futures::future::chain::Chain<A, B, C>>::poll
      14: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
      15: <futures::future::map::Map<A, F> as futures::future::Future>::poll
      16: <futures::future::either::Either<A, B> as futures::future::Future>::poll
      17: futures::task_impl::std::set
      18: futures::task_impl::std::ThreadNotify::with_current
      19: futures::future::Future::wait
      20: <jsonrpc_core::io::IoHandler<M>>::handle_request_sync
      21: migration_core::rpc_api::RpcApi::handle
      22: migration_engine::main
      23: std::rt::lang_start::{{closure}}
      24: std::panicking::try::do_call
      25: __rust_maybe_catch_panic
      26: std::rt::lang_start_internal
      27: main
```
